export class RecommendationsRequestDto {
  /** Search phrase generated by the LLM that should work well with Deezer search. */
  deezerQuery!: string;
  /**
   * Optional extra context (e.g. for future providers or simple fallbacks).
   * Not required by Deezer, but we keep it for flexibility.
   */
  genres?: string[];
}
